[versions]
jna_version = "5.14.0"

junit_version = "5.10.1"
mockito_version = "5.10.0"

[libraries]
jna = { module = "net.java.dev.jna:jna", version.ref = "jna_version" }
jna-platform-jpms = { module = "net.java.dev.jna:jna-platform-jpms", version.ref = "jna_version" }

junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit_version" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito_version" }
isofilereader = { module = "com.palantir.isofilereader:isofilereader", version = "0.6.0" }

[bundles]
jna = ["jna", "jna-platform-jpms"]
test = ["junit-jupiter", "mockito-core"]
